### ISSUE TITLE
Roadmap for next version

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#94]
Hi, Starting this thread to discuss and receive continuous feedbacks on roadmap for features/improvement in next version.

- [ ] Login button on Mobile view: Currently only Subscribe button is visible on Mobile view, not login button
- [ ] Ads: Feature to include at various places such as below header, in article etc. Option to disable ad for paid members only.
- [ ] Social media sharing icons: Tested on post with sidebar and are not available
- [ ] Last update date: Show last updated date on individual posts along with published date
- [ ] Follow menu: Separate follow button in header as like Mapache theme
- [ ] Google Lighthouse related improvements #90 

AMP specific

- [ ] Show author profile photo on post: Currently its shown on Non-AMP pages

More to be updated.

**Comment by yogeshbeniwal** [comment]
Updated results above after testing with v0.3.4. Using Post Sidebar Template.

**Comment by godofredoninja** [comment]
Hi

- **Last update date**: It happens is that it breaks a little the design, at the moment the last update of the post is in the title of the <time> tag.
- **Author social media icons**: The theme is inspired by médium. It would be nice to collect data if users click on the share icons. For example in my case it works for me.
- **Follow menu**: Simply has a [heder with the dropdown](https://github.com/godofredoninja/simply/blob/master/docs/layouts.md#header-with-dropdown-menu) you could use that dropdown for social media.
